# Generated by Django 4.0.3 on 2022-08-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NextSalesReceiptNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesPersonVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_number', models.SmallIntegerField()),
                ('sales_person_id', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModelVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('picture_url', models.URLField()),
                ('model_id', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PendingSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_number', models.SmallIntegerField(default=0, null=True)),
                ('vin', models.CharField(default='Waiting for VIN', max_length=17, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_and_time', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.SmallIntegerField()),
                ('made_downpayment', models.BooleanField(default=False)),
                ('loan_approved', models.BooleanField(default=False)),
                ('paid_full_cost', models.BooleanField(default=False)),
                ('vehicle_registered', models.BooleanField(default=False)),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_receipts', to='sales_rest.salespersonvo')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interested_customer', to='sales_rest.vehiclevo')),
            ],
        ),
    ]
