# Generated by Django 4.0.3 on 2022-08-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_vehiclevo_odometer_vehiclevo_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingsale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pendingsale',
            name='vin',
        ),
    ]
