# Generated by Django 4.0.3 on 2022-08-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_remove_pendingsale_price_remove_pendingsale_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsale',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingsale',
            name='vehicle_delivered',
            field=models.BooleanField(default=True),
        ),
    ]
