# Generated by Django 4.0.3 on 2022-08-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_pendingsale_pending_pendingsale_vehicle_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodelvo',
            name='picture_url',
        ),
    ]
