# Generated by Django 4.0.3 on 2022-08-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_remove_vehiclemodelvo_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclevo',
            name='price',
        ),
    ]
