# Generated by Django 4.0.3 on 2022-08-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0008_remove_pendingsale_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevo',
            name='pending',
            field=models.BooleanField(null=True),
        ),
    ]
