# Generated by Django 4.0.3 on 2022-08-16 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_vehiclevo_odometer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodelvo',
            name='picture_url',
        ),
    ]
