# Generated by Django 4.0.3 on 2022-08-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0004_automobile_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='pending',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
